# Generated by Django 5.2.6 on 2025-09-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('title', models.TextField(db_index=True)),
                ('description', models.TextField(db_index=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('thumbnail_url', models.URLField(null=True)),
                ('channel_title', models.CharField(db_index=True, max_length=256, null=True)),
            ],
        ),
    ]
